In [1]:
# Logistic Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [2]:
# Importing DataSet
from google.colab import drive
dataset=pd.read_csv('/content/customer_Data.csv')
dataset.head(10)

User_ID  Gender  Age  P_Code  C_Order
0  15793813       1   31   89000        0
1  15694395       1   24   32000        0
2  15764195       1   18   44000        0
3  15744919       1   29   83000        0
4  15671655       1   35   23000        0
5  15654901       1   27   58000        0
6  15649136       1   24   55000        0
7  15775562       1   23   48000        0
8  15807481       0   28   79000        0
9  15726358       1   24   27000        0

In [4]:
X = dataset.iloc[:, [0,1,2,3]].values
y = dataset.iloc[:, -1].values
print(X)
print(y)



[[15793813        1       31    89000]
 [15694395        1       24    32000]
 [15764195        1       18    44000]
 [15744919        1       29    83000]
 [15671655        1       35    23000]
 [15654901        1       27    58000]
 [15649136        1       24    55000]
 [15775562        1       23    48000]
 [15807481        0       28    79000]
 [15726358        1       24    27000]
 [15595228        1       20    23000]
 [15782530        1       33   113000]
 [15592877        0       32    18000]
 [15651983        0       34   112000]
 [15746737        0       18    52000]
 [15774179        1       22    27000]
 [15667265        1       28    87000]
 [15655123        1       26    17000]
 [15595917        0       30    80000]
 [15744279        0       32   100000]
 [15670619        0       25    90000]
 [15599533        1       37    33000]
 [15757837        0       35    38000]
 [15697574        1       33    69000]
 [15578738        1       18    86000]
 [15762228        1      

In [6]:
# Splitting the dataset into Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)



In [7]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [8]:

# Fitting Logistic Regression to the training set
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)



LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
# Predicting the Test set results
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)



[[17  1]
 [ 0 12]]


In [10]:
# Finding accuracy
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

0.9666666666666667


In [11]:
# Finding recall
from sklearn.metrics import recall_score
recall=recall_score(y_test,y_pred,average="binary")
print(recall)

1.0


In [12]:
# Finding precision
from sklearn.metrics import precision_score
precision=precision_score(y_test,y_pred,average="binary")
print(precision)

0.9230769230769231


In [13]:
# Finding F1 score
from sklearn.metrics import f1_score
f1Score=f1_score(y_test,y_pred,average="binary")
print(f1Score)

0.9600000000000001
